#Requires -Version 5.1
<#
.SYNOPSIS
  Prints governance/debt-report.json: grouped metrics, full table, optional deltas vs governance-previous/debt-report.json.
#>
$ErrorActionPreference = 'Stop'
$here = $PSScriptRoot
$repoRoot = Split-Path -Parent $here
$reportPath = Join-Path $here 'debt-report.json'
$prevPath = Join-Path $repoRoot 'governance-previous\debt-report.json'

if (-not (Test-Path $reportPath)) {
    Write-Host "No debt-report.json at $reportPath (run scan-debt.ps1 first)." -ForegroundColor Yellow
    exit 0
}

$j = Get-Content $reportPath -Raw -Encoding UTF8 | ConvertFrom-Json

function Get-ReportValue($name) {
    if (-not ($j.PSObject.Properties.Name -contains $name)) { return $null }
    return $j.$name
}

Write-Host '=== Governance metrics by area (this run) ===' -ForegroundColor Cyan

Write-Host "`n[Concurrency]" -ForegroundColor Yellow
Write-Host ("  {0,-45} {1}" -f 'conflictProblemDetailsCount', (Get-ReportValue 'conflictProblemDetailsCount'))
Write-Host ("  {0,-45} {1}" -f 'concurrencyExceptionHandlingCount', (Get-ReportValue 'concurrencyExceptionHandlingCount'))
Write-Host ("  {0,-45} {1}" -f 'concurrencyReadyEntityCount', (Get-ReportValue 'concurrencyReadyEntityCount'))
Write-Host ("  {0,-45} {1}" -f 'concurrencyTokenEntityCount', (Get-ReportValue 'concurrencyTokenEntityCount'))
Write-Host ("  {0,-45} {1}" -f 'concurrencyUpgradePlannedEntityCount', (Get-ReportValue 'concurrencyUpgradePlannedEntityCount'))
Write-Host ("  {0,-45} {1}" -f 'concurrencyWarningLogCount', (Get-ReportValue 'concurrencyWarningLogCount'))
Write-Host ("  {0,-45} {1}" -f 'optimisticConcurrencyEntityCount', (Get-ReportValue 'optimisticConcurrencyEntityCount'))

Write-Host "`n[Replay / idempotency]" -ForegroundColor Yellow
Write-Host ("  {0,-45} {1}" -f 'replaySensitiveProcessorCount', (Get-ReportValue 'replaySensitiveProcessorCount'))
Write-Host ("  {0,-45} {1}" -f 'moneyReplayRiskProcessorCount', (Get-ReportValue 'moneyReplayRiskProcessorCount'))
Write-Host ("  {0,-45} {1}" -f 'moneyPathReplayRiskCount', (Get-ReportValue 'moneyPathReplayRiskCount'))
Write-Host ("  {0,-45} {1}" -f 'missingDurableIdempotencyCommentCount', (Get-ReportValue 'missingDurableIdempotencyCommentCount'))
Write-Host ("  {0,-45} {1}" -f 'syncReplayRiskCommentCount', (Get-ReportValue 'syncReplayRiskCommentCount'))
Write-Host ("  {0,-45} {1}" -f 'explicitReplayWarningCount', (Get-ReportValue 'explicitReplayWarningCount'))
Write-Host ("  {0,-45} {1}" -f 'idempotencyShortCircuitLogCount', (Get-ReportValue 'idempotencyShortCircuitLogCount'))
Write-Host ("  {0,-45} {1}" -f 'idempotencyWarningLogCount', (Get-ReportValue 'idempotencyWarningLogCount'))
Write-Host ("  {0,-45} {1}" -f 'replaySensitiveMoneyProcessorCount', (Get-ReportValue 'replaySensitiveMoneyProcessorCount'))
Write-Host ("  {0,-45} {1}" -f 'durableReplayProtectedProcessorCount', (Get-ReportValue 'durableReplayProtectedProcessorCount'))
Write-Host ("  {0,-45} {1}" -f 'customerShiftReplayProtectedProcessorCount', (Get-ReportValue 'customerShiftReplayProtectedProcessorCount'))
Write-Host ("  {0,-45} {1}" -f 'replayProtectedCustomerShiftProcessorCount', (Get-ReportValue 'replayProtectedCustomerShiftProcessorCount'))
Write-Host ("  {0,-45} {1}" -f 'customerShiftReplayVisibilityCount', (Get-ReportValue 'customerShiftReplayVisibilityCount'))
Write-Host ("  {0,-45} {1}" -f 'inventoryReplayProtectedProcessorCount', (Get-ReportValue 'inventoryReplayProtectedProcessorCount'))
Write-Host ("  {0,-45} {1}" -f 'replayProtectedInventoryProcessorCount', (Get-ReportValue 'replayProtectedInventoryProcessorCount'))
Write-Host ("  {0,-45} {1}" -f 'inventoryReplayReceiptCount', (Get-ReportValue 'inventoryReplayReceiptCount'))
Write-Host ("  {0,-45} {1}" -f 'replayReceiptEntityCount', (Get-ReportValue 'replayReceiptEntityCount'))
Write-Host ("  {0,-45} {1}" -f 'replayReceiptLookupCount', (Get-ReportValue 'replayReceiptLookupCount'))
Write-Host ("  {0,-45} {1}" -f 'replayReceiptUniqueIndexCount', (Get-ReportValue 'replayReceiptUniqueIndexCount'))
Write-Host ("  {0,-45} {1}" -f 'syncBatchClassificationCount', (Get-ReportValue 'syncBatchClassificationCount'))
Write-Host ("  {0,-45} {1}" -f 'replayShortCircuitClassificationCount', (Get-ReportValue 'replayShortCircuitClassificationCount'))
Write-Host ("  {0,-45} {1}" -f 'partialBatchObservabilityAnchorCount', (Get-ReportValue 'partialBatchObservabilityAnchorCount'))
Write-Host ("  {0,-45} {1}" -f 'placeholderClassificationCount', (Get-ReportValue 'placeholderClassificationCount'))

Write-Host "`n[Operational reconciliation]" -ForegroundColor Yellow
Write-Host ("  {0,-45} {1}" -f 'reconciliationWarningCount', (Get-ReportValue 'reconciliationWarningCount'))
Write-Host ("  {0,-45} {1}" -f 'partialBatchReplayWarningCount', (Get-ReportValue 'partialBatchReplayWarningCount'))
Write-Host ("  {0,-45} {1}" -f 'partialBatchWarningCount', (Get-ReportValue 'partialBatchWarningCount'))

Write-Host "`n[Sync / placeholders]" -ForegroundColor Yellow
Write-Host ("  {0,-45} {1}" -f 'placeholderReplayGovernanceCount', (Get-ReportValue 'placeholderReplayGovernanceCount'))
Write-Host ("  {0,-45} {1}" -f 'placeholderProcessorCount', (Get-ReportValue 'placeholderProcessorCount'))
Write-Host ("  {0,-45} {1}" -f 'protectedPlaceholderProcessorCount', (Get-ReportValue 'protectedPlaceholderProcessorCount'))
Write-Host ("  {0,-45} {1}" -f 'moneyAffectingPlaceholderProcessorCount', (Get-ReportValue 'moneyAffectingPlaceholderProcessorCount'))

Write-Host "`n[Transaction / money-path anchors]" -ForegroundColor Yellow
Write-Host ("  {0,-45} {1}" -f 'transactionBoundaryAnchorCount', (Get-ReportValue 'transactionBoundaryAnchorCount'))
Write-Host ("  {0,-45} {1}" -f 'transactionBoundaryLogAnchorCount', (Get-ReportValue 'transactionBoundaryLogAnchorCount'))
Write-Host ("  {0,-45} {1}" -f 'explicitTransactionCount', (Get-ReportValue 'explicitTransactionCount'))
Write-Host ("  {0,-45} {1}" -f 'moneyPathGovernanceAnchorCount', (Get-ReportValue 'moneyPathGovernanceAnchorCount'))
Write-Host ("  {0,-45} {1}" -f 'inventoryConsistencyWarningCount', (Get-ReportValue 'inventoryConsistencyWarningCount'))
Write-Host ("  {0,-45} {1}" -f 'inventoryMovementObservabilityCount', (Get-ReportValue 'inventoryMovementObservabilityCount'))
Write-Host ("  {0,-45} {1}" -f 'inventoryReversalMovementCount', (Get-ReportValue 'inventoryReversalMovementCount'))
Write-Host ("  {0,-45} {1}" -f 'reversalObservabilityAnchorCount', (Get-ReportValue 'reversalObservabilityAnchorCount'))
Write-Host ("  {0,-45} {1}" -f 'paidVoidReversalProtectionCount', (Get-ReportValue 'paidVoidReversalProtectionCount'))
Write-Host ("  {0,-45} {1}" -f 'reversalTransactionBoundaryCount', (Get-ReportValue 'reversalTransactionBoundaryCount'))
Write-Host ("  {0,-45} {1}" -f 'reversalConcurrencyHandlingCount', (Get-ReportValue 'reversalConcurrencyHandlingCount'))
Write-Host ("  {0,-45} {1}" -f 'refundConsistencyAnchorCount', (Get-ReportValue 'refundConsistencyAnchorCount'))
Write-Host ("  {0,-45} {1}" -f 'refundPersistenceCount', (Get-ReportValue 'refundPersistenceCount'))
Write-Host ("  {0,-45} {1}" -f 'refundIdempotencyProtectionCount', (Get-ReportValue 'refundIdempotencyProtectionCount'))
Write-Host ("  {0,-45} {1}" -f 'overpaymentObservabilityCount', (Get-ReportValue 'overpaymentObservabilityCount'))
Write-Host ("  {0,-45} {1}" -f 'settlementObservabilityCount', (Get-ReportValue 'settlementObservabilityCount'))
Write-Host ("  {0,-45} {1}" -f 'syncConflictRecordCount', (Get-ReportValue 'syncConflictRecordCount'))
Write-Host ("  {0,-45} {1}" -f 'reconciliationObservabilityCount', (Get-ReportValue 'reconciliationObservabilityCount'))
Write-Host ("  {0,-45} {1}" -f 'inventoryDriftConflictCount', (Get-ReportValue 'inventoryDriftConflictCount'))
Write-Host ("  {0,-45} {1}" -f 'lifecycleConflictCount', (Get-ReportValue 'lifecycleConflictCount'))
Write-Host ("  {0,-45} {1}" -f 'replayMismatchConflictCount', (Get-ReportValue 'replayMismatchConflictCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalAuditRecordCount', (Get-ReportValue 'operationalAuditRecordCount'))
Write-Host ("  {0,-45} {1}" -f 'auditObservabilityAnchorCount', (Get-ReportValue 'auditObservabilityAnchorCount'))
Write-Host ("  {0,-45} {1}" -f 'timelineReconstructionCount', (Get-ReportValue 'timelineReconstructionCount'))
Write-Host ("  {0,-45} {1}" -f 'financialAuditAnchorCount', (Get-ReportValue 'financialAuditAnchorCount'))
Write-Host ("  {0,-45} {1}" -f 'reconciliationAuditAnchorCount', (Get-ReportValue 'reconciliationAuditAnchorCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalAuditEndpointCount', (Get-ReportValue 'operationalAuditEndpointCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalTimelineQueryCount', (Get-ReportValue 'operationalTimelineQueryCount'))
Write-Host ("  {0,-45} {1}" -f 'conflictDiagnosticsCount', (Get-ReportValue 'conflictDiagnosticsCount'))
Write-Host ("  {0,-45} {1}" -f 'auditPaginationProtectionCount', (Get-ReportValue 'auditPaginationProtectionCount'))
Write-Host ("  {0,-45} {1}" -f 'internalDiagnosticsAuthorizationCount', (Get-ReportValue 'internalDiagnosticsAuthorizationCount'))
Write-Host ("  {0,-45} {1}" -f 'reconciliationWorkflowEndpointCount', (Get-ReportValue 'reconciliationWorkflowEndpointCount'))
Write-Host ("  {0,-45} {1}" -f 'reconciliationStatusTransitionCount', (Get-ReportValue 'reconciliationStatusTransitionCount'))
Write-Host ("  {0,-45} {1}" -f 'reconciliationAuditActionCount', (Get-ReportValue 'reconciliationAuditActionCount'))
Write-Host ("  {0,-45} {1}" -f 'unresolvedConflictQueryCount', (Get-ReportValue 'unresolvedConflictQueryCount'))
Write-Host ("  {0,-45} {1}" -f 'reconciliationSummaryCount', (Get-ReportValue 'reconciliationSummaryCount'))
Write-Host ("  {0,-45} {1}" -f 'forensicExportEndpointCount', (Get-ReportValue 'forensicExportEndpointCount'))
Write-Host ("  {0,-45} {1}" -f 'forensicSnapshotGenerationCount', (Get-ReportValue 'forensicSnapshotGenerationCount'))
Write-Host ("  {0,-45} {1}" -f 'forensicMetadataSanitizationCount', (Get-ReportValue 'forensicMetadataSanitizationCount'))
Write-Host ("  {0,-45} {1}" -f 'forensicTimelineAggregationCount', (Get-ReportValue 'forensicTimelineAggregationCount'))
Write-Host ("  {0,-45} {1}" -f 'forensicAuthorizationProtectionCount', (Get-ReportValue 'forensicAuthorizationProtectionCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalRetentionProtectionCount', (Get-ReportValue 'operationalRetentionProtectionCount'))
Write-Host ("  {0,-45} {1}" -f 'forensicTruncationObservabilityCount', (Get-ReportValue 'forensicTruncationObservabilityCount'))
Write-Host ("  {0,-45} {1}" -f 'retentionSummaryEndpointCount', (Get-ReportValue 'retentionSummaryEndpointCount'))
Write-Host ("  {0,-45} {1}" -f 'agedConflictClassificationCount', (Get-ReportValue 'agedConflictClassificationCount'))
Write-Host ("  {0,-45} {1}" -f 'exportSurvivabilityMetadataCount', (Get-ReportValue 'exportSurvivabilityMetadataCount'))
Write-Host ("  {0,-45} {1}" -f 'queryClampProtectionCount', (Get-ReportValue 'queryClampProtectionCount'))
Write-Host ("  {0,-45} {1}" -f 'degradedModeClassificationCount', (Get-ReportValue 'degradedModeClassificationCount'))
Write-Host ("  {0,-45} {1}" -f 'resilienceEndpointCount', (Get-ReportValue 'resilienceEndpointCount'))
Write-Host ("  {0,-45} {1}" -f 'replayStormVisibilityCount', (Get-ReportValue 'replayStormVisibilityCount'))
Write-Host ("  {0,-45} {1}" -f 'exportPressureClassificationCount', (Get-ReportValue 'exportPressureClassificationCount'))
Write-Host ("  {0,-45} {1}" -f 'auditPersistenceResilienceCount', (Get-ReportValue 'auditPersistenceResilienceCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalPressureIndicatorCount', (Get-ReportValue 'operationalPressureIndicatorCount'))
Write-Host ("  {0,-45} {1}" -f 'backpressureObservabilityCount', (Get-ReportValue 'backpressureObservabilityCount'))
Write-Host ("  {0,-45} {1}" -f 'incidentCorrelationEndpointCount', (Get-ReportValue 'incidentCorrelationEndpointCount'))
Write-Host ("  {0,-45} {1}" -f 'causalityObservabilityCount', (Get-ReportValue 'causalityObservabilityCount'))
Write-Host ("  {0,-45} {1}" -f 'correlatedRiskClassificationCount', (Get-ReportValue 'correlatedRiskClassificationCount'))
Write-Host ("  {0,-45} {1}" -f 'cascadingDegradationCount', (Get-ReportValue 'cascadingDegradationCount'))
Write-Host ("  {0,-45} {1}" -f 'forensicIncidentEnrichmentCount', (Get-ReportValue 'forensicIncidentEnrichmentCount'))
Write-Host ("  {0,-45} {1}" -f 'replayIncidentAggregationCount', (Get-ReportValue 'replayIncidentAggregationCount'))
Write-Host ("  {0,-45} {1}" -f 'incidentSeverityClassificationCount', (Get-ReportValue 'incidentSeverityClassificationCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalAlertSignalCount', (Get-ReportValue 'operationalAlertSignalCount'))
Write-Host ("  {0,-45} {1}" -f 'criticalAlertVisibilityCount', (Get-ReportValue 'criticalAlertVisibilityCount'))
Write-Host ("  {0,-45} {1}" -f 'alertEscalationObservabilityCount', (Get-ReportValue 'alertEscalationObservabilityCount'))
Write-Host ("  {0,-45} {1}" -f 'replayPressureAlertCount', (Get-ReportValue 'replayPressureAlertCount'))
Write-Host ("  {0,-45} {1}" -f 'inventoryRiskAlertCount', (Get-ReportValue 'inventoryRiskAlertCount'))
Write-Host ("  {0,-45} {1}" -f 'alertDiagnosticsEndpointCount', (Get-ReportValue 'alertDiagnosticsEndpointCount'))
Write-Host ("  {0,-45} {1}" -f 'cacheHitObservabilityCount', (Get-ReportValue 'cacheHitObservabilityCount'))
Write-Host ("  {0,-45} {1}" -f 'cacheMissObservabilityCount', (Get-ReportValue 'cacheMissObservabilityCount'))
Write-Host ("  {0,-45} {1}" -f 'cacheTtlGovernanceCount', (Get-ReportValue 'cacheTtlGovernanceCount'))
Write-Host ("  {0,-45} {1}" -f 'staleRiskVisibilityCount', (Get-ReportValue 'staleRiskVisibilityCount'))
Write-Host ("  {0,-45} {1}" -f 'resilienceCacheReuseCount', (Get-ReportValue 'resilienceCacheReuseCount'))
Write-Host ("  {0,-45} {1}" -f 'cachePressureBypassCount', (Get-ReportValue 'cachePressureBypassCount'))
Write-Host ("  {0,-45} {1}" -f 'staleSnapshotRiskCount', (Get-ReportValue 'staleSnapshotRiskCount'))
Write-Host ("  {0,-45} {1}" -f 'reconciliationCacheReuseCount', (Get-ReportValue 'reconciliationCacheReuseCount'))
Write-Host ("  {0,-45} {1}" -f 'incidentCacheReuseCount', (Get-ReportValue 'incidentCacheReuseCount'))
Write-Host ("  {0,-45} {1}" -f 'incidentGroupReuseCount', (Get-ReportValue 'incidentGroupReuseCount'))
Write-Host ("  {0,-45} {1}" -f 'alertCacheReuseCount', (Get-ReportValue 'alertCacheReuseCount'))
Write-Host ("  {0,-45} {1}" -f 'forensicCompactSummaryCount', (Get-ReportValue 'forensicCompactSummaryCount'))
Write-Host ("  {0,-45} {1}" -f 'forensicLiveExportProtectionCount', (Get-ReportValue 'forensicLiveExportProtectionCount'))
Write-Host ("  {0,-45} {1}" -f 'cachedOperationalCompositionCount', (Get-ReportValue 'cachedOperationalCompositionCount'))
Write-Host ("  {0,-45} {1}" -f 'cacheDiagnosticsEndpointCount', (Get-ReportValue 'cacheDiagnosticsEndpointCount'))
Write-Host ("  {0,-45} {1}" -f 'cacheEffectivenessVisibilityCount', (Get-ReportValue 'cacheEffectivenessVisibilityCount'))
Write-Host ("  {0,-45} {1}" -f 'cacheMetadataProjectionCount', (Get-ReportValue 'cacheMetadataProjectionCount'))
Write-Host ("  {0,-45} {1}" -f 'cachePressureVisibilityCount', (Get-ReportValue 'cachePressureVisibilityCount'))
Write-Host ("  {0,-45} {1}" -f 'cacheInvalidationCount', (Get-ReportValue 'cacheInvalidationCount'))
Write-Host ("  {0,-45} {1}" -f 'scopedCacheKeyCount', (Get-ReportValue 'scopedCacheKeyCount'))
Write-Host ("  {0,-45} {1}" -f 'alertCacheLayerCount', (Get-ReportValue 'alertCacheLayerCount'))
Write-Host ("  {0,-45} {1}" -f 'cacheFreshnessRecoveryCount', (Get-ReportValue 'cacheFreshnessRecoveryCount'))
Write-Host ("  {0,-45} {1}" -f 'targetedInvalidationHookCount', (Get-ReportValue 'targetedInvalidationHookCount'))
Write-Host ("  {0,-45} {1}" -f 'adaptiveTtlReductionCount', (Get-ReportValue 'adaptiveTtlReductionCount'))
Write-Host ("  {0,-45} {1}" -f 'warmCandidateVisibilityCount', (Get-ReportValue 'warmCandidateVisibilityCount'))
Write-Host ("  {0,-45} {1}" -f 'cacheReadinessSignalCount', (Get-ReportValue 'cacheReadinessSignalCount'))
Write-Host ("  {0,-45} {1}" -f 'cacheStabilityClassificationCount', (Get-ReportValue 'cacheStabilityClassificationCount'))
Write-Host ("  {0,-45} {1}" -f 'predictiveWarmRecommendationCount', (Get-ReportValue 'predictiveWarmRecommendationCount'))
Write-Host ("  {0,-45} {1}" -f 'cacheCardinalityGovernanceCount', (Get-ReportValue 'cacheCardinalityGovernanceCount'))
Write-Host ("  {0,-45} {1}" -f 'cacheGovernanceOverviewCount', (Get-ReportValue 'cacheGovernanceOverviewCount'))
Write-Host ("  {0,-45} {1}" -f 'cachePressureClassificationCount', (Get-ReportValue 'cachePressureClassificationCount'))
Write-Host ("  {0,-45} {1}" -f 'cacheDegradationVisibilityCount', (Get-ReportValue 'cacheDegradationVisibilityCount'))
Write-Host ("  {0,-45} {1}" -f 'scopedCacheSurvivabilityCount', (Get-ReportValue 'scopedCacheSurvivabilityCount'))
Write-Host ("  {0,-45} {1}" -f 'cacheScopeChurnVisibilityCount', (Get-ReportValue 'cacheScopeChurnVisibilityCount'))
Write-Host ("  {0,-45} {1}" -f 'governanceAuditProjectionCount', (Get-ReportValue 'governanceAuditProjectionCount'))
Write-Host ("  {0,-45} {1}" -f 'governanceDriftVisibilityCount', (Get-ReportValue 'governanceDriftVisibilityCount'))
Write-Host ("  {0,-45} {1}" -f 'diagnosticsConsistencyVisibilityCount', (Get-ReportValue 'diagnosticsConsistencyVisibilityCount'))
Write-Host ("  {0,-45} {1}" -f 'survivabilityClassificationCount', (Get-ReportValue 'survivabilityClassificationCount'))
Write-Host ("  {0,-45} {1}" -f 'operatorRecommendationVisibilityCount', (Get-ReportValue 'operatorRecommendationVisibilityCount'))
Write-Host ("  {0,-45} {1}" -f 'cacheExplainabilitySignalCount', (Get-ReportValue 'cacheExplainabilitySignalCount'))
Write-Host ("  {0,-45} {1}" -f 'cacheInvalidationAuditCount', (Get-ReportValue 'cacheInvalidationAuditCount'))
Write-Host ("  {0,-45} {1}" -f 'freshnessRecoveryVisibilityCount', (Get-ReportValue 'freshnessRecoveryVisibilityCount'))
Write-Host ("  {0,-45} {1}" -f 'crossCategoryInvalidationCount', (Get-ReportValue 'crossCategoryInvalidationCount'))
Write-Host ("  {0,-45} {1}" -f 'cacheRecoveryGuidanceCount', (Get-ReportValue 'cacheRecoveryGuidanceCount'))
Write-Host ("  {0,-45} {1}" -f 'invalidationDriftVisibilityCount', (Get-ReportValue 'invalidationDriftVisibilityCount'))
Write-Host ("  {0,-45} {1}" -f 'consistencyRecoveryVisibilityCount', (Get-ReportValue 'consistencyRecoveryVisibilityCount'))
Write-Host ("  {0,-45} {1}" -f 'containmentGovernanceCount', (Get-ReportValue 'containmentGovernanceCount'))
Write-Host ("  {0,-45} {1}" -f 'propagationDiagnosticsCount', (Get-ReportValue 'propagationDiagnosticsCount'))
Write-Host ("  {0,-45} {1}" -f 'consistencyConfidenceVisibilityCount', (Get-ReportValue 'consistencyConfidenceVisibilityCount'))
Write-Host ("  {0,-45} {1}" -f 'recoveryStabilizationSignalCount', (Get-ReportValue 'recoveryStabilizationSignalCount'))
Write-Host ("  {0,-45} {1}" -f 'pressureLifecycleGovernanceCount', (Get-ReportValue 'pressureLifecycleGovernanceCount'))
Write-Host ("  {0,-45} {1}" -f 'pressureRecoveryGovernanceCount', (Get-ReportValue 'pressureRecoveryGovernanceCount'))
Write-Host ("  {0,-45} {1}" -f 'pressureConvergenceGovernanceCount', (Get-ReportValue 'pressureConvergenceGovernanceCount'))
Write-Host ("  {0,-45} {1}" -f 'pressureResetCoordinatorCount', (Get-ReportValue 'pressureResetCoordinatorCount'))
Write-Host ("  {0,-45} {1}" -f 'pressureStabilizationResetCount', (Get-ReportValue 'pressureStabilizationResetCount'))
Write-Host ("  {0,-45} {1}" -f 'governanceExplainabilityComposerCount', (Get-ReportValue 'governanceExplainabilityComposerCount'))
Write-Host ("  {0,-45} {1}" -f 'governanceCompositionContextCount', (Get-ReportValue 'governanceCompositionContextCount'))
Write-Host ("  {0,-45} {1}" -f 'governanceProjectionCollaboratorCount', (Get-ReportValue 'governanceProjectionCollaboratorCount'))
Write-Host ("  {0,-45} {1}" -f 'governanceSurfaceBudgetCount', (Get-ReportValue 'governanceSurfaceBudgetCount'))
Write-Host ("  {0,-45} {1}" -f 'governanceThresholdEvaluatorCount', (Get-ReportValue 'governanceThresholdEvaluatorCount'))
Write-Host ("  {0,-45} {1}" -f 'governanceModuleRegistryCount', (Get-ReportValue 'governanceModuleRegistryCount'))
Write-Host ("  {0,-45} {1}" -f 'governancePipelineStageCount', (Get-ReportValue 'governancePipelineStageCount'))
Write-Host ("  {0,-45} {1}" -f 'governanceConventionsCount', (Get-ReportValue 'governanceConventionsCount'))
Write-Host ("  {0,-45} {1}" -f 'governanceComplexityBudgetCount', (Get-ReportValue 'governanceComplexityBudgetCount'))
Write-Host ("  {0,-45} {1}" -f 'governanceRuntimeProtectionCount', (Get-ReportValue 'governanceRuntimeProtectionCount'))
Write-Host ("  {0,-45} {1}" -f 'telemetrySaturationVisibilityCount', (Get-ReportValue 'telemetrySaturationVisibilityCount'))
Write-Host ("  {0,-45} {1}" -f 'governanceFailsafeVisibilityCount', (Get-ReportValue 'governanceFailsafeVisibilityCount'))
Write-Host ("  {0,-45} {1}" -f 'runtimeBudgetEnforcementCount', (Get-ReportValue 'runtimeBudgetEnforcementCount'))
Write-Host ("  {0,-45} {1}" -f 'projectionComplexityClassificationCount', (Get-ReportValue 'projectionComplexityClassificationCount'))
Write-Host ("  {0,-45} {1}" -f 'governanceSnapshotReuseCount', (Get-ReportValue 'governanceSnapshotReuseCount'))
Write-Host ("  {0,-45} {1}" -f 'projectionReuseVisibilityCount', (Get-ReportValue 'projectionReuseVisibilityCount'))
Write-Host ("  {0,-45} {1}" -f 'snapshotConsistencyVisibilityCount', (Get-ReportValue 'snapshotConsistencyVisibilityCount'))
Write-Host ("  {0,-45} {1}" -f 'governanceSnapshotFreshnessCount', (Get-ReportValue 'governanceSnapshotFreshnessCount'))
Write-Host ("  {0,-45} {1}" -f 'projectionReuseEfficiencyCount', (Get-ReportValue 'projectionReuseEfficiencyCount'))
Write-Host ("  {0,-45} {1}" -f 'governanceFingerprintVisibilityCount', (Get-ReportValue 'governanceFingerprintVisibilityCount'))
Write-Host ("  {0,-45} {1}" -f 'governanceDriftAnalysisCount', (Get-ReportValue 'governanceDriftAnalysisCount'))
Write-Host ("  {0,-45} {1}" -f 'replayConsistencyVisibilityCount', (Get-ReportValue 'replayConsistencyVisibilityCount'))
Write-Host ("  {0,-45} {1}" -f 'governanceSignatureTransitionCount', (Get-ReportValue 'governanceSignatureTransitionCount'))
Write-Host ("  {0,-45} {1}" -f 'projectionFingerprintDeterminismCount', (Get-ReportValue 'projectionFingerprintDeterminismCount'))
Write-Host ("  {0,-45} {1}" -f 'runtimeBaselineVisibilityCount', (Get-ReportValue 'runtimeBaselineVisibilityCount'))
Write-Host ("  {0,-45} {1}" -f 'governanceComplexityReductionCount', (Get-ReportValue 'governanceComplexityReductionCount'))
Write-Host ("  {0,-45} {1}" -f 'governanceExecutionBudgetCount', (Get-ReportValue 'governanceExecutionBudgetCount'))
Write-Host ("  {0,-45} {1}" -f 'governanceProductionReadinessCount', (Get-ReportValue 'governanceProductionReadinessCount'))
Write-Host ("  {0,-45} {1}" -f 'governanceFreezeRecommendationCount', (Get-ReportValue 'governanceFreezeRecommendationCount'))
Write-Host ("  {0,-45} {1}" -f 'governanceFreezeEnforcementCount', (Get-ReportValue 'governanceFreezeEnforcementCount'))
Write-Host ("  {0,-45} {1}" -f 'governanceDeadSurfaceVisibilityCount', (Get-ReportValue 'governanceDeadSurfaceVisibilityCount'))
Write-Host ("  {0,-45} {1}" -f 'governanceDeterminismAuditCount', (Get-ReportValue 'governanceDeterminismAuditCount'))
Write-Host ("  {0,-45} {1}" -f 'governanceRuntimeConsistencyCount', (Get-ReportValue 'governanceRuntimeConsistencyCount'))
Write-Host ("  {0,-45} {1}" -f 'governanceOwnershipBoundaryCount', (Get-ReportValue 'governanceOwnershipBoundaryCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalDashboardAggregationCount', (Get-ReportValue 'operationalDashboardAggregationCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalDashboardHealthVisibilityCount', (Get-ReportValue 'operationalDashboardHealthVisibilityCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalDashboardRecommendationCount', (Get-ReportValue 'operationalDashboardRecommendationCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalDashboardReadModelCount', (Get-ReportValue 'operationalDashboardReadModelCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalWorkbenchAggregationCount', (Get-ReportValue 'operationalWorkbenchAggregationCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalWorkbenchAttentionVisibilityCount', (Get-ReportValue 'operationalWorkbenchAttentionVisibilityCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalWorkbenchReplayRiskVisibilityCount', (Get-ReportValue 'operationalWorkbenchReplayRiskVisibilityCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalWorkbenchInventoryDriftCount', (Get-ReportValue 'operationalWorkbenchInventoryDriftCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalInventoryWorkbenchAggregationCount', (Get-ReportValue 'operationalInventoryWorkbenchAggregationCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalInventoryDriftVisibilityCount', (Get-ReportValue 'operationalInventoryDriftVisibilityCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalInventoryResolutionVisibilityCount', (Get-ReportValue 'operationalInventoryResolutionVisibilityCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalInventoryHotspotCount', (Get-ReportValue 'operationalInventoryHotspotCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalReplayWorkbenchAggregationCount', (Get-ReportValue 'operationalReplayWorkbenchAggregationCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalReplayPressureVisibilityCount', (Get-ReportValue 'operationalReplayPressureVisibilityCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalReplayRecoveryConfidenceCount', (Get-ReportValue 'operationalReplayRecoveryConfidenceCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalReplayHotspotCount', (Get-ReportValue 'operationalReplayHotspotCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalCompositionHubCount', (Get-ReportValue 'operationalCompositionHubCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalCompositionReuseCount', (Get-ReportValue 'operationalCompositionReuseCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalCompositionDepthReductionCount', (Get-ReportValue 'operationalCompositionDepthReductionCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalTrendAggregationCount', (Get-ReportValue 'operationalTrendAggregationCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalTrendDeltaVisibilityCount', (Get-ReportValue 'operationalTrendDeltaVisibilityCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalTrendWindowCount', (Get-ReportValue 'operationalTrendWindowCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalTrendAttentionCount', (Get-ReportValue 'operationalTrendAttentionCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalNavigationAggregationCount', (Get-ReportValue 'operationalNavigationAggregationCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalNavigationRouteCount', (Get-ReportValue 'operationalNavigationRouteCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalNavigationAttentionCount', (Get-ReportValue 'operationalNavigationAttentionCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalNavigationRecommendationCount', (Get-ReportValue 'operationalNavigationRecommendationCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalTimelineAggregationCount', (Get-ReportValue 'operationalTimelineAggregationCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalTimelineCorrelationCount', (Get-ReportValue 'operationalTimelineCorrelationCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalTimelineRetentionCount', (Get-ReportValue 'operationalTimelineRetentionCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalTimelineAttentionCount', (Get-ReportValue 'operationalTimelineAttentionCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalTriageAggregationCount', (Get-ReportValue 'operationalTriageAggregationCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalTriagePriorityCount', (Get-ReportValue 'operationalTriagePriorityCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalTriageCorrelationCount', (Get-ReportValue 'operationalTriageCorrelationCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalTriageRecommendationCount', (Get-ReportValue 'operationalTriageRecommendationCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalRecoveryAggregationCount', (Get-ReportValue 'operationalRecoveryAggregationCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalRecoveryConvergenceCount', (Get-ReportValue 'operationalRecoveryConvergenceCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalRecoveryOutlookCount', (Get-ReportValue 'operationalRecoveryOutlookCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalRecoveryConfidenceCount', (Get-ReportValue 'operationalRecoveryConfidenceCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalIncidentAggregationCount', (Get-ReportValue 'operationalIncidentAggregationCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalIncidentRecurrenceCount', (Get-ReportValue 'operationalIncidentRecurrenceCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalIncidentInvestigationCount', (Get-ReportValue 'operationalIncidentInvestigationCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalIncidentRetentionCount', (Get-ReportValue 'operationalIncidentRetentionCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalCausalityAggregationCount', (Get-ReportValue 'operationalCausalityAggregationCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalCausalityPropagationCount', (Get-ReportValue 'operationalCausalityPropagationCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalCausalityBlockerCount', (Get-ReportValue 'operationalCausalityBlockerCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalCausalityContinuityCount', (Get-ReportValue 'operationalCausalityContinuityCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalSituationRoomAggregationCount', (Get-ReportValue 'operationalSituationRoomAggregationCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalExecutiveBriefingCount', (Get-ReportValue 'operationalExecutiveBriefingCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalNarrativeSynthesisCount', (Get-ReportValue 'operationalNarrativeSynthesisCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalAttentionCount', (Get-ReportValue 'operationalAttentionCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalSimulationAggregationCount', (Get-ReportValue 'operationalSimulationAggregationCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalStabilizationScenarioCount', (Get-ReportValue 'operationalStabilizationScenarioCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalDegradationScenarioCount', (Get-ReportValue 'operationalDegradationScenarioCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalLeverageInterpretationCount', (Get-ReportValue 'operationalLeverageInterpretationCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalPlaybookAggregationCount', (Get-ReportValue 'operationalPlaybookAggregationCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalStabilizationGuidanceCount', (Get-ReportValue 'operationalStabilizationGuidanceCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalEscalationGuidanceCount', (Get-ReportValue 'operationalEscalationGuidanceCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalResponseSequencingCount', (Get-ReportValue 'operationalResponseSequencingCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalPatternAggregationCount', (Get-ReportValue 'operationalPatternAggregationCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalArchetypeRecognitionCount', (Get-ReportValue 'operationalArchetypeRecognitionCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalStabilizationPatternCount', (Get-ReportValue 'operationalStabilizationPatternCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalEscalationPatternCount', (Get-ReportValue 'operationalEscalationPatternCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalIntegrityAggregationCount', (Get-ReportValue 'operationalIntegrityAggregationCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalContradictionDetectionCount', (Get-ReportValue 'operationalContradictionDetectionCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalNarrativeAlignmentCount', (Get-ReportValue 'operationalNarrativeAlignmentCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalCoherenceCount', (Get-ReportValue 'operationalCoherenceCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalExperienceGraphAggregationCount', (Get-ReportValue 'operationalExperienceGraphAggregationCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalTraversalGenerationCount', (Get-ReportValue 'operationalTraversalGenerationCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalContextualNavigationCount', (Get-ReportValue 'operationalContextualNavigationCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalRelationshipCount', (Get-ReportValue 'operationalRelationshipCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalDigestAggregationCount', (Get-ReportValue 'operationalDigestAggregationCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalHighlightCount', (Get-ReportValue 'operationalHighlightCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalExecutiveDigestCount', (Get-ReportValue 'operationalExecutiveDigestCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalNavigationHighlightCount', (Get-ReportValue 'operationalNavigationHighlightCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalEvolutionAggregationCount', (Get-ReportValue 'operationalEvolutionAggregationCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalTransitionCount', (Get-ReportValue 'operationalTransitionCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalMomentumInterpretationCount', (Get-ReportValue 'operationalMomentumInterpretationCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalEvolutionContinuityCount', (Get-ReportValue 'operationalEvolutionContinuityCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalTopologyAggregationCount', (Get-ReportValue 'operationalTopologyAggregationCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalDependencyChainCount', (Get-ReportValue 'operationalDependencyChainCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalInfluenceInterpretationCount', (Get-ReportValue 'operationalInfluenceInterpretationCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalTopologyContinuityCount', (Get-ReportValue 'operationalTopologyContinuityCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalConvergenceAggregationCount', (Get-ReportValue 'operationalConvergenceAggregationCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalReinforcementInterpretationCount', (Get-ReportValue 'operationalReinforcementInterpretationCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalAmbiguityAnalysisCount', (Get-ReportValue 'operationalAmbiguityAnalysisCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalDivergenceInterpretationCount', (Get-ReportValue 'operationalDivergenceInterpretationCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalResilienceCognitionAggregationCount', (Get-ReportValue 'operationalResilienceCognitionAggregationCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalSurvivabilityInterpretationCount', (Get-ReportValue 'operationalSurvivabilityInterpretationCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalFragilityAnalysisCount', (Get-ReportValue 'operationalFragilityAnalysisCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalContainmentDurabilityCount', (Get-ReportValue 'operationalContainmentDurabilityCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalAttentionAggregationCount', (Get-ReportValue 'operationalAttentionAggregationCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalPriorityInterpretationCount', (Get-ReportValue 'operationalPriorityInterpretationCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalAttentionCoordinationCount', (Get-ReportValue 'operationalAttentionCoordinationCount'))
Write-Host ("  {0,-45} {1}" -f 'operationalEmphasisCount', (Get-ReportValue 'operationalEmphasisCount'))
Write-Host ("  {0,-45} {1}" -f 'strategyAggregationCount', (Get-ReportValue 'strategyAggregationCount'))
Write-Host ("  {0,-45} {1}" -f 'strategicAlignmentCount', (Get-ReportValue 'strategicAlignmentCount'))
Write-Host ("  {0,-45} {1}" -f 'coordinationInterpretationCount', (Get-ReportValue 'coordinationInterpretationCount'))
Write-Host ("  {0,-45} {1}" -f 'strategyContinuityCount', (Get-ReportValue 'strategyContinuityCount'))
Write-Host ("  {0,-45} {1}" -f 'equilibriumAggregationCount', (Get-ReportValue 'equilibriumAggregationCount'))
Write-Host ("  {0,-45} {1}" -f 'imbalanceInterpretationCount', (Get-ReportValue 'imbalanceInterpretationCount'))
Write-Host ("  {0,-45} {1}" -f 'pressureDistributionCount', (Get-ReportValue 'pressureDistributionCount'))
Write-Host ("  {0,-45} {1}" -f 'equilibriumContinuityCount', (Get-ReportValue 'equilibriumContinuityCount'))
Write-Host ("  {0,-45} {1}" -f 'changeDueProtectionCount', (Get-ReportValue 'changeDueProtectionCount'))
Write-Host ("  {0,-45} {1}" -f 'netCapturedRefundCount', (Get-ReportValue 'netCapturedRefundCount'))
Write-Host ("  {0,-45} {1}" -f 'overpaymentSettlementCount', (Get-ReportValue 'overpaymentSettlementCount'))
Write-Host ("  {0,-45} {1}" -f 'taxDivergenceGovernanceCount', (Get-ReportValue 'taxDivergenceGovernanceCount'))
Write-Host ("  {0,-45} {1}" -f 'moneyInventoryReplayClassificationCount', (Get-ReportValue 'moneyInventoryReplayClassificationCount'))

Write-Host "`n[Placeholder / risk comments]" -ForegroundColor Yellow
Write-Host ("  {0,-45} {1}" -f 'governanceRiskCommentCount', (Get-ReportValue 'governanceRiskCommentCount'))
Write-Host ("  {0,-45} {1}" -f 'governanceWarningLogCount', (Get-ReportValue 'governanceWarningLogCount'))

Write-Host "`n[OpenAPI]" -ForegroundColor Yellow
Write-Host ("  {0,-45} {1}" -f 'OpenAPITrackedPathCount', (Get-ReportValue 'OpenAPITrackedPathCount'))

Write-Host "`n[Advisory visibility (not a fix; upgrade separately)]" -ForegroundColor Yellow
Write-Host ("  {0,-45} {1}" -f 'knownNugetAutoMapperAdvisoryCount', (Get-ReportValue 'knownNugetAutoMapperAdvisoryCount'))
Write-Host '  Note: AutoMapper NU1903 is accepted for now; see ARCHITECTURE_DEBT_REPORT.md / IMPROVEMENT_REPORT.md.'

Write-Host "`n=== All debt-report fields (sorted) ===" -ForegroundColor Cyan
$j.PSObject.Properties.Name | Sort-Object | ForEach-Object {
    $v = $j.$_
    Write-Host ("  {0,-40} {1}" -f $_, $v)
}

if (Test-Path $prevPath) {
    Write-Host "`n=== Debt metric deltas (current - previous artifact) ===" -ForegroundColor Cyan
    $prev = Get-Content $prevPath -Raw -Encoding UTF8 | ConvertFrom-Json
    $keys = @($j.PSObject.Properties.Name + $prev.PSObject.Properties.Name) | Sort-Object -Unique
    $any = $false
    foreach ($k in $keys) {
        if ($k.StartsWith('_') -or $k -eq 'lastGeneratedUtc') { continue }
        try {
            $a = [double]$j.$k
            $b = [double]$prev.$k
        }
        catch {
            continue
        }
        $d = $a - $b
        if ($d -ne 0) {
            Write-Host ("  {0}: {1} -> {2} (delta {3:+g})" -f $k, $b, $a, $d)
            $any = $true
        }
    }
    if (-not $any) {
        Write-Host '  (no numeric deltas vs previous artifact)' -ForegroundColor DarkGray
    }
}
else {
    Write-Host "`nINFO: No governance-previous/debt-report.json; skipping delta block (typical on main or first run)." -ForegroundColor DarkGray
}
